package org.uml.explorer;

import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.util.Collection;
import java.util.Set;
import javax.swing.tree.TreeSelectionModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.api.visual.model.ObjectScene;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.Lookup.Result;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.windows.WindowManager;
import org.uml.model.ClassDiagram;
import org.uml.model.components.ComponentBase;
import org.uml.model.members.MemberBase;

/**
 * Top component which displays something. See:
 *
 * http://platform.netbeans.org/tutorials/nbm-selection-1.html
 * http://platform.netbeans.org/tutorials/nbm-selection-2.html
 * http://platform.netbeans.org/tutorials/nbm-nodesapi3.html
 * http://wiki.netbeans.org/BasicUnderstandingOfTheNetBeansNodesAPI
 *
 *
 * http://netbeans-org.1045718.n5.nabble.com/TopComponent-associateLookup-is-incompatible-with-setActivatedNodes-is-it-a-bug-td3261230.html
 */
@ConvertAsProperties(
        dtd = "-//org.uml.explorer.ide.navigator//Explorer//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "easyUMLExplorerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "navigator", openAtStartup = false)
@ActionID(category = "Window", id = "org.uml.explorer.ExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ExplorerAction",
        preferredID = "easyUMLExplorerTopComponent")
@Messages({
    "CTL_ExplorerAction=easyUML Explorer",
    "CTL_ExplorerTopComponent=easyUML Explorer",
    "HINT_ExplorerTopComponent=Class diagram hierarchy"
})
public final class ExplorerTopComponent extends TopComponent implements ExplorerManager.Provider, LookupListener {

    /**
     * Manager of the nodes that is returned for ExplorerManager.Provider interface
     */
    private final ExplorerManager explorerManager = new ExplorerManager();
    /**
     * Tree view that is shown in the TopComponent. Finds the explorer manager in the parents
     * and shows the content based on it.
     */
    private final BeanTreeView explorerTree;

    /**
     * The current object scene. Used for recognising if corresponding UMLTopComponent is open.
     */
    private ObjectScene currentObjectScene;

    /**
     * Listeners for model component selection in ClassDiagramScene in UMLTopComponent.
     */
    private Result<ClassDiagram> resultCD;
    private Result<ComponentBase> resultC;
    private Result<MemberBase> resultM;

    /**
     * Default constructor. Initializes the TopComponent, adds the tree as a view
     * and adds right-click actions for nodes.
     */
    public ExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_ExplorerTopComponent());
        setToolTipText(Bundle.HINT_ExplorerTopComponent());

        explorerTree = new BeanTreeView();
        explorerTree.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        add(explorerTree, BorderLayout.CENTER);

        getActionMap().put("delete", ExplorerUtils.actionDelete(explorerManager, true));
        associateLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()));

        explorerTree.setRootVisible(false);
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    /**
     * Sets the current class diagram scene which corresponds to root diagram.
     * Used when activating UMLTopComponent, as diagram does not change from
     * ClassDiagramDataObject to UMLTopComponent, they are the same, so the
     * lookup event does not fire and currentObjectScene remains null.
     *
     * @param currentObjectScene
     */
    public void setCurrentObjectScene(ObjectScene currentObjectScene) {
        this.currentObjectScene = currentObjectScene;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        resultCD = Utilities.actionsGlobalContext().lookupResult(ClassDiagram.class);
        resultC = Utilities.actionsGlobalContext().lookupResult(ComponentBase.class);
        resultM = Utilities.actionsGlobalContext().lookupResult(MemberBase.class);
        addLookupListeners();
    }

    @Override
    public void componentClosed() {
        removeLookupListeners();
    }

    @Override
    protected void componentDeactivated() {
        super.componentDeactivated();
        updateWhenEmpty();
    }
    
    private void updateWhenEmpty(){
        // When deactivating ExplorerTopComponent, deselect all nodes, except when we are accessing linked TCs
        if (!isActivatedLinkedTC()) {
            emptyTree();
        } else {
            if(isDeselectAllSituation()){
                deselectAllNodes();
            }
        }
    }

    /**
     * Used to enable selection detection from ClassDiagramScene.
     */
    private void addLookupListeners() {
        resultCD.addLookupListener(this);
        resultC.addLookupListener(this);
        resultM.addLookupListener(this);
    }

    /**
     * Used to disable selection detection from ClassDiagramScene, while changing selection in explorer (avoid loop selections).
     */
    private void removeLookupListeners() {
        resultCD.removeLookupListener(this);
        resultC.removeLookupListener(this);
        resultM.removeLookupListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    /**
     * Adapting selection based on lookup result from ClassDiagramScene or projectsLogicalTC
     *
     * @param ev
     */
    @Override
    @SuppressWarnings({"unchecked", "rawtypes"})
    public void resultChanged(LookupEvent ev) {
        Lookup.Result source = (Lookup.Result) ev.getSource();
        Collection instances = source.allInstances();
        if (!instances.isEmpty()) {
            for (Object instance : instances) {
                if (instance instanceof ClassDiagram) {
                    initializeRoot((ClassDiagram) instance);
                    ObjectScene os = Utilities.actionsGlobalContext().lookup(ObjectScene.class);
                    if(os != null) setCurrentObjectScene(os);
                } else if (instance instanceof ComponentBase) {
                    selectComponentNode((ComponentBase) instance);
                } else if (instance instanceof MemberBase) {
                    selectMemberNode((MemberBase) instance);
                }
                // Process only the first of the instances (selection limited do 1)
                break;
            }
        } else {
            updateWhenEmpty();
        }
        repaint();
        validate();
    }

    public void initializeRoot(ClassDiagram selectedDiagram) {
        if (!isValidDiagramInRoot(selectedDiagram)) {
            createRootNode(selectedDiagram);
        }
        if (!isDeselectAllSituation()) {
            selectNode(explorerManager.getRootContext());
        }
    }

    private boolean isActivatedLinkedTC() {
        // current activated
        TopComponent activatedTC = WindowManager.getDefault().getRegistry().getActivated();
        if (activatedTC == null) return false;
        // linked
        // TODO tight coupling. Can this be done better?
        TopComponent projectsLogicalTC = WindowManager.getDefault().findTopComponent("projectTabLogical_tc");
        ClassDiagram projectsSelectedClassDiagram = projectsLogicalTC.getLookup().lookup(ClassDiagram.class);
        TopComponent propertiesTC = WindowManager.getDefault().findTopComponent("properties");
        TopComponent paletteTC = WindowManager.getDefault().findTopComponent("CommonPalette");
        TopComponent navigatorTC = WindowManager.getDefault().findTopComponent("navigatorTC");

        if (activatedTC == this && isCurrentRootSceneOpened()
                || activatedTC == this && isValidDiagramInRoot(projectsSelectedClassDiagram)
                || activatedTC == projectsLogicalTC && isValidDiagramInRoot(projectsSelectedClassDiagram)
                || activatedTC == paletteTC && isCurrentRootSceneOpened()
                || activatedTC == propertiesTC
                || activatedTC == navigatorTC
                || isUMLTopComponent(activatedTC) && isRootCorrespondingToUMLTC(activatedTC)) {
            return true;
        } else {
            return false;
        }
    }

    private boolean isDeselectAllSituation() {
        TopComponent activatedTC = WindowManager.getDefault().getRegistry().getActivated();
        TopComponent paletteTC = WindowManager.getDefault().findTopComponent("CommonPalette");
        TopComponent projectsLogicalTC = WindowManager.getDefault().findTopComponent("projectTabLogical_tc");
        if (activatedTC == paletteTC && isCurrentRootSceneOpened() || activatedTC == projectsLogicalTC) {
            return true;
        } else {
            return false;
        }
    }

    private boolean isCurrentRootSceneOpened() {
        Set<TopComponent> tcs = WindowManager.getDefault().getRegistry().getOpened();
        for (TopComponent tc : tcs) {
            if (isUMLTopComponent(tc)) {
                ObjectScene os = tc.getLookup().lookup(ObjectScene.class);
                if (os.equals(currentObjectScene))
                    return true;
            }
        }
        return false;
    }

    public boolean isValidDiagramInRoot(ClassDiagram diagram) {
        Node rootNode = explorerManager.getRootContext();
        if (rootNode instanceof ClassDiagramNode) { // on opening of file, root is AbstractNode, that's why we need this check
            ClassDiagramNode root = (ClassDiagramNode) rootNode;
            if (root.getClassDiagram() == diagram) {
                return true;
            }
        }
        deselectAllNodes();
        return false;
    }

    private boolean isRootCorrespondingToUMLTC(TopComponent tc) {
        Node rootNode = explorerManager.getRootContext();
        if (rootNode instanceof ClassDiagramNode) { // on opening of file, root is AbstractNode, that's why we need this check
            ObjectScene tcObjectScene = tc.getLookup().lookup(ObjectScene.class);
            if (currentObjectScene != null && currentObjectScene.equals(tcObjectScene)) return true;
        }
        return false;
    }

    private boolean isUMLTopComponent(TopComponent tc) {
        if (tc.getClass().getSimpleName().equals("UMLTopComponent")) return true;
        else return false;
    }

    public void emptyTree() {
        removeLookupListeners();
        explorerTree.setRootVisible(false);
        explorerManager.setRootContext(Node.EMPTY);
        addLookupListeners();
    }

    private Node createRootNode(ClassDiagram diagram) {
        ClassDiagramNode node = new ClassDiagramNode(diagram, currentObjectScene);
        explorerManager.setRootContext(node);
        explorerTree.setRootVisible(true);
        return node;
    }

    private void selectComponentNode(ComponentBase component) {
        if (!isValidDiagramInRoot(component.getParentDiagram())) {
            createRootNode(component.getParentDiagram());
        }
        for (Node cn : getExplorerManager().getRootContext().getChildren().getNodes()) {
            ComponentNode componentNode = (ComponentNode) cn;
            if (componentNode.getComponent() == component) {
                selectNode(componentNode);
                return;
            }
        }
    }

    private void selectMemberNode(MemberBase member) {
        if (!isValidDiagramInRoot(member.getDeclaringComponent().getParentDiagram())) {
            createRootNode(member.getDeclaringComponent().getParentDiagram());
        }
        for (Node cn : getExplorerManager().getRootContext().getChildren().getNodes()) {
            for (Node mn : cn.getChildren().getNodes()) {
                MemberNode memberNode = (MemberNode) mn;
                if (memberNode.getMember() == member) {
                    selectNode(memberNode);
                    return;
                }
            }
        }
    }

    /**
     * Select node in the tree. If null is passed, selection is cleared.
     *
     * @param node
     */
    private void selectNode(Node node) {
        removeLookupListeners();
        try {
            if (node != null) getExplorerManager().setSelectedNodes(new Node[]{node});
            else getExplorerManager().setSelectedNodes(new Node[]{});
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);
        }
        addLookupListeners();
    }

    private void deselectAllNodes() {
        selectNode(null);
    }
}
