/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.uml.visual.dialogs;

import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;

/**
 *
 * @author gosselin
 */
public class CustomSizePanel extends javax.swing.JPanel {

    private DialogDescriptor dd;
    private Dialog dialog;
    private JButton btnOK = new JButton("OK");
    private JButton btnCancel = new JButton("Cancel");   
    private int customWidth, customHeight;
    private boolean ok;
    
    
    /**
     * Creates new form CustomSizePanel
     */
    public CustomSizePanel(int width,int height) {
        initComponents();
        customWidth = width;
        customHeight = height;
        jTextField1.setText(Integer.toString(width));
        jTextField2.setText(Integer.toString(height));   
        ok = false;
        btnOK.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                customWidth = Integer.parseInt(jTextField1.getText());
                customHeight = Integer.parseInt(jTextField2.getText());
                ok = true;
            }
        });
        btnCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialog.dispose();
            }
        });
    }

    public int getWidth() {
        return customWidth;
    }
    
    public int getHeight() {
        return customHeight;
    }
    
    public boolean openDialog() {
        dd = new DialogDescriptor(this, "Select custom size", true, new Object[]{btnOK, btnCancel}, null, DialogDescriptor.DEFAULT_ALIGN, null, null);
        dialog = DialogDisplayer.getDefault().createDialog(dd);
        //dialog.setPreferredSize(new Dimension(400,100));
        dialog.setVisible(true);
        return ok;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 50));
        setRequestFocusEnabled(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 7, 0, 7, 0};
        layout.rowHeights = new int[] {0, 7, 0};
        setLayout(layout);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CustomSizePanel.class, "CustomSizePanel.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);

        jTextField1.setText(org.openide.util.NbBundle.getMessage(CustomSizePanel.class, "CustomSizePanel.jTextField1.text")); // NOI18N
        jTextField1.setMinimumSize(new java.awt.Dimension(500, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextField1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CustomSizePanel.class, "CustomSizePanel.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel2, gridBagConstraints);

        jTextField2.setText(org.openide.util.NbBundle.getMessage(CustomSizePanel.class, "CustomSizePanel.jTextField2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextField2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
