package org.uml.visual.dialogs.unused;

import java.util.List;
import javax.swing.JComboBox;
import org.netbeans.api.visual.widget.Widget;
import org.uml.model.relations.CardinalityEnum;
import org.uml.visual.widgets.components.ClassWidget;
import org.uml.visual.widgets.components.ComponentWidgetBase;
import org.uml.visual.widgets.components.EnumWidget;

/**
 *
 * @author Uros
 * Active when CTRL-clicking dragging from component to component. 
 */
public class ClassUseRelationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClassUseRelationPanel
     */
    ComponentWidgetBase componentWidget;
    
    public ClassUseRelationPanel(ComponentWidgetBase widget) {
        initComponents();
        this.componentWidget=widget;
        lblRelationType.setText("Uses (dependency)");
        fillCombos(componentWidget);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        lblCardinalitySource = new javax.swing.JLabel();
        cbxCardinalitySource = new javax.swing.JComboBox<CardinalityEnum>();
        lblCardinalityTarget = new javax.swing.JLabel();
        cbxCardinalityTarget = new javax.swing.JComboBox<CardinalityEnum>();
        lblTarget = new javax.swing.JLabel();
        cbxTarget = new javax.swing.JComboBox<Widget>();
        lblRelation = new javax.swing.JLabel();
        lblRelationType = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblSourceClass = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(lblName, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblName.text")); // NOI18N

        txfName.setText(org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.txfName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblCardinalitySource, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblCardinalitySource.text")); // NOI18N

        cbxCardinalitySource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCardinalitySourceActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblCardinalityTarget, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblCardinalityTarget.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblTarget, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblTarget.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblRelation, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblRelation.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblRelationType, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblRelationType.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblSource, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblSource.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblSourceClass, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblSourceClass.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSource, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSourceClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxTarget, 0, 170, Short.MAX_VALUE)
                            .addComponent(lblRelationType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCardinalitySource)
                            .addComponent(lblCardinalityTarget))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCardinalityTarget, 0, 170, Short.MAX_VALUE)
                            .addComponent(cbxCardinalitySource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRelationType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRelation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSourceClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTarget)
                    .addComponent(cbxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardinalitySource)
                    .addComponent(cbxCardinalitySource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardinalityTarget)
                    .addComponent(cbxCardinalityTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCardinalitySourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCardinalitySourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCardinalitySourceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<CardinalityEnum> cbxCardinalitySource;
    private javax.swing.JComboBox<CardinalityEnum> cbxCardinalityTarget;
    private javax.swing.JComboBox<Widget> cbxTarget;
    private javax.swing.JLabel lblCardinalitySource;
    private javax.swing.JLabel lblCardinalityTarget;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRelation;
    private javax.swing.JLabel lblRelationType;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblSourceClass;
    private javax.swing.JLabel lblTarget;
    private javax.swing.JTextField txfName;
    // End of variables declaration//GEN-END:variables

    private void fillCombos(ComponentWidgetBase widget) {
        List<Widget> widgets =  componentWidget.getClassDiagramScene().getMainLayer().getChildren();
        for (Widget w : widgets) {
            if (!w.equals(widget) && w instanceof ComponentWidgetBase) {
                cbxTarget.addItem(w);
            }
        }
        
        lblSourceClass.setText(widget.getName());
        
        cbxCardinalitySource.addItem(CardinalityEnum.Zero2One);
        cbxCardinalitySource.addItem(CardinalityEnum.One2One);
        cbxCardinalitySource.addItem(CardinalityEnum.One2Many);
        cbxCardinalitySource.addItem(CardinalityEnum.Zero2Many);
        
        cbxCardinalityTarget.addItem(CardinalityEnum.Zero2One);
        cbxCardinalityTarget.addItem(CardinalityEnum.One2One);
        cbxCardinalityTarget.addItem(CardinalityEnum.One2Many);
        cbxCardinalityTarget.addItem(CardinalityEnum.Zero2Many);
    }
    
    public JComboBox<CardinalityEnum> getComboBoxCardinalitySource () {
        return cbxCardinalitySource;
    }
    
    public JComboBox<CardinalityEnum> getComboBoxCardinalityTarget () {
        return cbxCardinalityTarget;
    }

    public JComboBox<Widget> getComboBoxTarget() {
        return cbxTarget;
    }
    public String getRelationName () {
        return txfName.getText();
    }
}
