package org.uml.filetype;

import javax.swing.JPanel;
import javax.swing.JTextField;

public final class ClassDiagramVisualPanel1 extends JPanel {

    /**
     * Creates new form ClassDiagramVisualPanel1
     */
    public ClassDiagramVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Enter Diagram Name";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        classDiagramNameField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ClassDiagramVisualPanel1.class, "ClassDiagramVisualPanel1.jLabel1.text")); // NOI18N

        classDiagramNameField.setText(org.openide.util.NbBundle.getMessage(ClassDiagramVisualPanel1.class, "ClassDiagramVisualPanel1.classDiagramNameField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classDiagramNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(classDiagramNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        classDiagramNameField.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ClassDiagramVisualPanel1.class, "ClassDiagramVisualPanel1.classDiagramNameField.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField classDiagramNameField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JTextField getClassDiagramNameField() {
        return classDiagramNameField;
    }
    
}
