package org.uml.visual;

import java.awt.BorderLayout;
import java.util.Collection;
import javax.swing.JScrollPane;
import org.netbeans.api.project.Project;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.api.visual.widget.Widget;
import org.netbeans.spi.palette.PaletteController;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.filesystems.FileObject;
import org.openide.util.Lookup;
import org.openide.util.Lookup.Result;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;
import org.uml.model.ClassDiagram;
import org.uml.model.ClassDiagramComponent;
import org.uml.visual.palette.PaletteSupport;
import org.uml.visual.widgets.ClassDiagramScene;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.uml.visual//UML//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "UMLTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.uml.visual.UMLTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_UMLAction",
        preferredID = "UMLTopComponent")
@Messages({
    "CTL_UMLAction=UML",
    "CTL_UMLTopComponent=UML Window",
    "HINT_UMLTopComponent=This is a UML window"
})
public final class UMLTopComponent extends TopComponent /**implements LookupListener**/ {

    private ClassDiagram umlClassDiagram;
    private ClassDiagramScene classDiagramScene;
    PaletteController palette;
    private JScrollPane shapePane;

    public UMLTopComponent() {
        initComponents();
        setName(Bundle.CTL_UMLTopComponent());
        setToolTipText(Bundle.HINT_UMLTopComponent());
        classDiagramScene = new ClassDiagramScene(umlClassDiagram = new ClassDiagram());     // Fresh scene with fresh diagram
        shapePane = new JScrollPane();
        shapePane.setViewportView(classDiagramScene.createView());
        add(shapePane, BorderLayout.CENTER);
        add(classDiagramScene.createSatelliteView(), BorderLayout.WEST);
        palette = PaletteSupport.createPalette();
    }

    public UMLTopComponent(ClassDiagram cd) {
        umlClassDiagram = cd;
        initComponents();
        setName(cd.getName());
        setToolTipText(Bundle.HINT_UMLTopComponent());
        classDiagramScene = new ClassDiagramScene(cd);
        shapePane = new JScrollPane();
        shapePane.setViewportView(classDiagramScene.createView());
        add(shapePane, BorderLayout.CENTER);
        add(classDiagramScene.createSatelliteView(), BorderLayout.WEST);

        palette = PaletteSupport.createPalette();

        // napuni scenu komponentama
        //ovo se nalazi u konstruktoru scene, tako da treba da se ukloni odavde
//        for (ClassDiagramComponent comp : cd.getComponents().values()) {
//            Widget w = classDiagramScene.attach(comp);
//            w.setPreferredLocation();
//        }
        classDiagramScene.validate();

    }

    @Override
    public Lookup getLookup() {
        return new ProxyLookup(
                new Lookup[]{
            classDiagramScene.getLookup(),
            Lookups.singleton(umlClassDiagram),
//            Lookups.singleton(selectedProject),
            Lookups.singleton(palette)
        });

    }

//    public UMLTopComponent(ClassDiagram umlClassDiagram) {
//        this.umlClassDiagram = umlClassDiagram;
//        initComponents();
//        setName(Bundle.CTL_UMLTopComponent());
//        setToolTipText(Bundle.HINT_UMLTopComponent());
//        setLayout(new BorderLayout());
//        classDiagramScene = new ClassDiagramScene(this.umlClassDiagram);
//
//        //implementiraj
//        //scene.visualizeNetwork();
//       
//        associateLookup(Lookups.fixed(new Object[]{PaletteSupport.createPalette()}));
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(viewPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane viewPane;
    // End of variables declaration//GEN-END:variables
    Lookup.Result<Project> resultPrj;

    @Override
    public void componentOpened() {
        resultPrj = Utilities.actionsGlobalContext().lookupResult(Project.class);
//        resultPrj.addLookupListener(this);
    }

    @Override
    public void componentClosed() {
        //ViewManager.getInstance().onNetworkClose(umlClassDiagram);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
//    @Override
//    public Lookup getLookup() {
//        return new ProxyLookup(new Lookup[]{super.getLookup(),aLookup});
//    }
//    Project selectedProject;
//
//    @Override
//    public void resultChanged(LookupEvent le) {
//        Lookup.Result localResult = (Result)le.getSource();
//        Collection<Object> coll = localResult.allInstances();
//        if (!coll.isEmpty()){
//            for (Object selectedItem : coll){
//                if (selectedItem instanceof Project) selectedProject = (Project) selectedItem;
//            }
//        }
//        
//         FileObject folder = selectedProject.getProjectDirectory();
//         String path = folder.getPath();
//    }
}
