package org.uml.explorer;

import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.util.Collection;
import java.util.Set;
import javax.swing.tree.TreeSelectionModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.Lookup.Result;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.windows.WindowManager;
import org.uml.model.ClassDiagram;
import org.uml.model.components.ComponentBase;
import org.uml.model.members.MemberBase;

/**
 * Top component which displays something. See:
 *
 * http://platform.netbeans.org/tutorials/nbm-selection-1.html
 * http://platform.netbeans.org/tutorials/nbm-selection-2.html
 * http://platform.netbeans.org/tutorials/nbm-nodesapi3.html
 * http://wiki.netbeans.org/BasicUnderstandingOfTheNetBeansNodesAPI
 *
 *
 * http://netbeans-org.1045718.n5.nabble.com/TopComponent-associateLookup-is-incompatible-with-setActivatedNodes-is-it-a-bug-td3261230.html
 */
@ConvertAsProperties(
        dtd = "-//org.uml.explorer.ide.navigator//Explorer//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "ExplorerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "navigator", openAtStartup = false)
@ActionID(category = "Window", id = "org.uml.explorer.ExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ExplorerAction",
        preferredID = "ExplorerTopComponent")
@Messages({
    "CTL_ExplorerAction=Explorer",
    "CTL_ExplorerTopComponent=Explorer Window",
    "HINT_ExplorerTopComponent=This is a Explorer window"
})
public final class ExplorerTopComponent extends TopComponent implements ExplorerManager.Provider, LookupListener {

    private final ExplorerManager explorerManager = new ExplorerManager();
    private final BeanTreeView explorerTree;

    Result<ClassDiagram> resultCD;
    Result<ComponentBase> resultC;
    Result<MemberBase> resultM;

    public ExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_ExplorerTopComponent());
        setToolTipText(Bundle.HINT_ExplorerTopComponent());

        explorerTree = new BeanTreeView();
        explorerTree.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        add(explorerTree, BorderLayout.CENTER);

        getActionMap().put("delete", ExplorerUtils.actionDelete(explorerManager, true));
        associateLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()));

        explorerTree.setRootVisible(false);
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    public BeanTreeView getExplorerTree() {
        return explorerTree;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        resultCD = Utilities.actionsGlobalContext().lookupResult(ClassDiagram.class);
        resultCD.addLookupListener(this);
        // calls result changed on its own, no need for: 
//        resultChanged(new LookupEvent(resultCD));

        resultC = Utilities.actionsGlobalContext().lookupResult(ComponentBase.class);
        resultC.addLookupListener(this);

        resultM = Utilities.actionsGlobalContext().lookupResult(MemberBase.class);
        resultM.addLookupListener(this);
    }

    @Override
    protected void componentActivated() {
        super.componentActivated();
    }

    @Override
    protected void componentShowing() {
        super.componentShowing();
    }

    @Override
    public void componentClosed() {
        resultCD.removeLookupListener(this);
        resultC.removeLookupListener(this);
        resultM.removeLookupListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    @Override
    @SuppressWarnings({"unchecked", "rawtypes"})
    public void resultChanged(LookupEvent ev) {
        Lookup.Result source = (Lookup.Result) ev.getSource();
        Collection instances = source.allInstances();
        try {
            if (instances.isEmpty()) {
                Set<TopComponent> tcs = WindowManager.getDefault().getRegistry().getOpened();
                for (TopComponent tc : tcs) {
                    // This is made hardcoded, because we cannot access UMLTopComponent from here because of cyclic dependency
                    // TODO maybe rework
                    if (tc.getClass().getSimpleName().equals("UMLTopComponent")) {
                        repaint();
                        validate();
                        return;
                    }
                }

                explorerManager.setRootContext(Node.EMPTY);
                explorerTree.setRootVisible(false);
            } else {
                for (Object instance : instances) {
                    if (instance instanceof ClassDiagram) {
                        ClassDiagram diagram = (ClassDiagram) instance;
                        if (!(explorerManager.getRootContext() instanceof ClassDiagramNode)) {
                            ClassDiagramNode node = new ClassDiagramNode(diagram);
                            explorerManager.setRootContext(node);
                            explorerTree.setRootVisible(true);
                        } else {
                            ClassDiagramNode root = (ClassDiagramNode) explorerManager.getRootContext();
                            if (diagram != root.getClassDiagram()) {
                                ClassDiagramNode node = new ClassDiagramNode(diagram);
                                explorerManager.setRootContext(node);
                                explorerTree.setRootVisible(true);
                            } else {
                                explorerManager.setSelectedNodes(new Node[]{explorerManager.getRootContext()});
                            }
                        }
                    } else if (instance instanceof ComponentBase) {
                        ComponentBase component = (ComponentBase) instance;
                        for (Node n : explorerManager.getRootContext().getChildren().getNodes()) {
                            ComponentNode cn = (ComponentNode) n;
                            if (cn.getComponent() == component) {
                                explorerManager.setSelectedNodes(new Node[]{cn});
                                break;
                            }
                        }
                    } else if (instance instanceof MemberBase) {
                        MemberBase member = (MemberBase) instance;
                        boolean over = false;
                        for (Node n : explorerManager.getRootContext().getChildren().getNodes()) {
                            for (Node cn : n.getChildren().getNodes()) {
                                MemberNode mn = (MemberNode) cn;
                                if (mn.getMember() == member) {
                                    explorerManager.setSelectedNodes(new Node[]{mn});
                                    over = true;
                                    break;
                                }
                            }
                            if (over) break;
                        }
                    }
                    break;
                }
            }
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);
        }
        repaint();
        validate();
//        open();
        // ne moze uvek ovo
//        requestActive();
    }

}
