package org.uml.visual.dialogs;

import java.util.List;
import javax.swing.JComboBox;
import org.netbeans.api.visual.widget.Widget;
import org.uml.model.CardinalityEnum;
import org.uml.visual.widgets.ClassWidget;
import org.uml.visual.widgets.ComponentWidgetBase;
import org.uml.visual.widgets.EnumWidget;

/**
 *
 * @author Uros
 * Acrive when CTRL-clicking dragging from component to component. 
 */
public class ClassUseRelationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClassUseRelationPanel
     */
    ComponentWidgetBase componentWidget;
    
    public ClassUseRelationPanel(ComponentWidgetBase widget) {
        initComponents();
        this.componentWidget=widget;
        lblRelationType.setText("Uses (dependency)");
        fillCombos(componentWidget);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        labelCardinalitySource = new javax.swing.JLabel();
        comboBoxCardinalitySource = new javax.swing.JComboBox<CardinalityEnum>();
        labelCardinalityTarget = new javax.swing.JLabel();
        comboBoxCardinalityTarget = new javax.swing.JComboBox<CardinalityEnum>();
        jLabel1 = new javax.swing.JLabel();
        comboBoxTarget = new javax.swing.JComboBox<Widget>();
        lblRelation = new javax.swing.JLabel();
        lblRelationType = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblSourceClass = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.jLabel2.text")); // NOI18N

        textFieldName.setText(org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.textFieldName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(labelCardinalitySource, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.labelCardinalitySource.text")); // NOI18N

        comboBoxCardinalitySource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCardinalitySourceActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(labelCardinalityTarget, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.labelCardinalityTarget.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblRelation, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblRelation.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblRelationType, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblRelationType.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblSource, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblSource.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblSourceClass, org.openide.util.NbBundle.getMessage(ClassUseRelationPanel.class, "ClassUseRelationPanel.lblSourceClass.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSource, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSourceClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxTarget, 0, 170, Short.MAX_VALUE)
                            .addComponent(lblRelationType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCardinalitySource)
                            .addComponent(labelCardinalityTarget))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxCardinalityTarget, 0, 170, Short.MAX_VALUE)
                            .addComponent(comboBoxCardinalitySource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRelationType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRelation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSourceClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCardinalitySource)
                    .addComponent(comboBoxCardinalitySource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCardinalityTarget)
                    .addComponent(comboBoxCardinalityTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxCardinalitySourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCardinalitySourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCardinalitySourceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<CardinalityEnum> comboBoxCardinalitySource;
    private javax.swing.JComboBox<CardinalityEnum> comboBoxCardinalityTarget;
    private javax.swing.JComboBox<Widget> comboBoxTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCardinalitySource;
    private javax.swing.JLabel labelCardinalityTarget;
    private javax.swing.JLabel lblRelation;
    private javax.swing.JLabel lblRelationType;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblSourceClass;
    private javax.swing.JTextField textFieldName;
    // End of variables declaration//GEN-END:variables

    private void fillCombos(ComponentWidgetBase componentWidget) {
               
        List<Widget> widgets =  componentWidget.getClassDiagramScene().getMainLayer().getChildren();
        for (Widget w : widgets) {
            if ((w instanceof ClassWidget||w instanceof EnumWidget)&&!w.equals(componentWidget)) {
                comboBoxTarget.addItem(w);
            }
        }
        lblSourceClass.setText(componentWidget.getName());
        
        comboBoxCardinalitySource.addItem(CardinalityEnum.Zero2One);
        comboBoxCardinalitySource.addItem(CardinalityEnum.One2One);
        comboBoxCardinalitySource.addItem(CardinalityEnum.One2Many);
        comboBoxCardinalitySource.addItem(CardinalityEnum.Zero2Many);
        
        comboBoxCardinalityTarget.addItem(CardinalityEnum.Zero2One);
        comboBoxCardinalityTarget.addItem(CardinalityEnum.One2One);
        comboBoxCardinalityTarget.addItem(CardinalityEnum.One2Many);
        comboBoxCardinalityTarget.addItem(CardinalityEnum.Zero2Many);
    }
    
    public JComboBox<CardinalityEnum> getComboBoxCardinalitySource () {
        return comboBoxCardinalitySource;
    }
    
    public JComboBox<CardinalityEnum> getComboBoxCardinalityTarget () {
        return comboBoxCardinalityTarget;
    }

    public JComboBox<Widget> getComboBoxTarget() {
        return comboBoxTarget;
    }
    public String getRelationName () {
        return textFieldName.getText();
    }
}
