package org.uml.visual.dialogs;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import org.openide.windows.WindowManager;
import org.uml.model.components.ComponentBase;

/**
 *
 * @author Ilija
 */
public class EditPackageDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddClassDialog
     */
    private ComponentBase component;

    public EditPackageDialog(ComponentBase component) {
        super((Frame) null, true);
        initComponents();
        this.component = component;
        txfPackageName.setText(component.getParentPackage());
        txfPackageName.selectAll();
        txfPackageName.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnOk.doClick();
                }
            }
        });
        setLocationRelativeTo(WindowManager.getDefault().getMainWindow());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfPackageName = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(EditPackageDialog.class, "EditPackageDialog.title")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EditPackageDialog.class, "EditPackageDialog.jLabel1.text")); // NOI18N

        txfPackageName.setText(org.openide.util.NbBundle.getMessage(EditPackageDialog.class, "EditPackageDialog.txfPackageName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnOk, org.openide.util.NbBundle.getMessage(EditPackageDialog.class, "EditPackageDialog.btnOk.text")); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, org.openide.util.NbBundle.getMessage(EditPackageDialog.class, "EditPackageDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txfPackageName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfPackageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        component.setParentPackage(txfPackageName.getText());
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txfPackageName;
    // End of variables declaration//GEN-END:variables

    
//        System.out.println("INSTANCA COMPA JE TIPA: "+comp.getClass().getName());
//        //first to remove info from package that it contains component
//        PackageComponent p = comp.getParentPackage();
//        if (p != null && p.getComponents().containsKey(comp.getName())) {
//            p.removeComponent(comp);
//        }
//        //now to see if that package is empty (in that case, we have to remove it from ClassDiagram instance)
//        if (p != null && p.getComponents().isEmpty()) {
//            classDiagram.removePackage(p);
//            p = null;
//        }
//
//        //now we set information about package on Component's instance
//        String pack = txtPackageName.getText().trim();
//        if (classDiagram.getPackages().containsKey(pack)) {
//            PackageComponent packageComp = classDiagram.getPackages().get(pack);
//            comp.setParentPackage(packageComp);
//            packageComp.addComponent(comp);
//        } else {
//            PackageComponent packComp = new PackageComponent(classDiagram, pack);
//            classDiagram.addPackage(packComp);
//            comp.setParentPackage(packComp);
//            System.out.println("COMP NAME: " + comp.getName());
//            packComp.addComponent(comp);
//        }
//
//        System.out.println("Test to see all packages on classDiagram");
//
//        for (Map.Entry<String, PackageComponent> entry : classDiagram.getPackages().entrySet()) {
//            String name = entry.getKey();
//            PackageComponent value = entry.getValue();
//            value.printAllComponentsOnStdOut();
//        }
//
//        System.out.println("-------------------------------------------------------------------");
//
//
////        for (ClassDiagramComponent cdc : classDiagram.getComponents()){
////            System.out.println("Name: "+cdc.getName()+"\t Package: "+ cdc.getParentPackage().getName());
////        }
//        for (Map.Entry<String, ComponentBase> entry : classDiagram.getComponents().entrySet()) {
//            String name = entry.getKey();
//            ComponentBase cdc = entry.getValue();
//            if (cdc.getParentPackage() != null) {
//                System.out.println("Name: " + cdc.getName() + "\t Package: " + cdc.getParentPackage().getName());
//            }
//
//        }
////        System.out.println("////////////////////////////////////////////////////////////");
////        System.out.println("Now for packages");
////        for (Map.Entry<String, PackageComponent> entry : classDiagram.getPackages().entrySet()) {
////            String name = entry.getKey();
////            PackageComponent packageComponent = entry.getValue();
////            String components = "";
////            
////            
////            System.out.println("Name: "+name+" \t Components: " );
////        }
//
////        comp.setParentPackage(new PackageComponent(pack));
//        this.dispose();
}
